Update README.md
DeveloperParana/conduta pull request #4
Opened 2022-12-27 14:42 UTC by endersonmenezes

2022-12-27 17:15 UTC, DaniloTerra approved these changes

2023-02-04 17:13 UTC, guiseek requested changes
Só um detalhe ali, acho que já falei sobre isso contigo

2023-02-04 17:13 UTC, guiseek commented on README.md
> -O Dev Paraná é uma comunidade dedicada a oferecer um ambiente livre de assédio para todos, independentemente do sexo, identidade de gênero e expressão, idade, orientação sexual, deficiência, aparênci
não fica estranho "O DevParaná é umA comunidade" ? acho que seria legal trocar por A DevParaná é uma comunidade...

2023-02-04 17:13 UTC, guiseek commented on README.md
> +O DevParaná é uma comunidade dedicada a oferecer um ambiente livre de assédio para todos, independentemente do sexo, identidade de gênero e expressão, idade, orientação sexual, deficiência, aparência
Aqui também

2023-02-04 18:14 UTC, guiseek reviewed
ajustes de O DevParaná para A DevParaná

2023-02-04 18:25 UTC, endersonmenezes commented
> ajustes de O DevParaná para A DevParaná

Positivo, acabei de ler. LGTM 😃

2023-02-04 18:26 UTC, guiseek approved these changes

2023-02-04 18:28 UTC, merged