cross-posting
DeveloperParana/conduta pull request #5
Opened 2024-10-31 00:24 UTC by GeovaneNorbert

Adicionado termo de cross-posting no codigo de conduta.

2024-10-31 00:56 UTC, ferfabricio requested changes
NJ! somente um detalhe quanto a formatação

2024-10-31 00:56 UTC, ferfabricio commented on README.md
> +**4.3 Cross-Posting Inadequado**
Por favor utilizar a mesma formatação dos outros itens, título com `####` e os itens com `*`

2024-10-31 14:09 UTC, ByIvo commented on README.md
> +
O conteúdo está bom, só gostaria de sugerir pra acrescentamos algo como:

Obs: Se você considera seu conteúdo relevante para toda a comunidade, procure algum administrador para criar um anúncio que será disseminado para toda a comunidade de uma só vez.

2024-11-05 00:31 UTC, ByIvo approved these changes

2024-11-05 00:32 UTC, merged